In [1]:
#Array oprationsans

In [2]:
import numpy as np

In [3]:
#Arithmatic oprations

In [9]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr1 + arr2

array([ 7,  9, 11, 13, 15])

In [11]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [13]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [14]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [16]:
arr = np.array([1,2,3,4])
arr + 10                    #Broadcasting

array([11, 12, 13, 14])

In [17]:
arr3 = np.arange(1,26).reshape(5,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
arr3+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [20]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [21]:
B = np.array([[5,6],[7,8]])
B

array([[5, 6],
       [7, 8]])

In [22]:
A @ B

array([[19, 22],
       [43, 50]])

In [23]:
A.T

array([[1, 3],
       [2, 4]])

In [24]:
B.T

array([[5, 7],
       [6, 8]])

In [25]:
A@B

array([[19, 22],
       [43, 50]])

In [26]:
#Stacking

In [27]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [28]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
# splitting array

In [32]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [34]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]