In [11]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,2.4,"Hello"]
a

[1, 2, 2.4, 'Hello']

In [7]:
np.array(a)

array(['1', '2', '2.4', 'Hello'], dtype='<U32')

In [8]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
## Array Generation Function

In [20]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [21]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [25]:
arr = np.linspace(1,10,100)
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [26]:
## Random Generation Function

In [27]:
arr = np.random.rand(4)
arr

array([0.8684768 , 0.75391628, 0.66624192, 0.67454712])

In [31]:
arr = np.random.randn(4)
arr

array([-1.25080898, -0.61164586,  2.01272394,  0.20612269])

In [32]:
arr = np.random.randint(10,20,5)
arr

array([11, 17, 10, 16, 16], dtype=int32)

In [34]:
## Array Attributes


In [38]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr1.shape

(3, 3)

In [43]:
arr1.size

9

In [44]:
## Array methods


In [12]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.sum(arr2,axis = 1)

array([ 6, 15, 24])

In [14]:
np.sum(arr2,axis = 0)

array([12, 15, 18])

In [16]:
arr2.mean()

np.float64(5.0)

In [18]:
arr2.std()

np.float64(2.581988897471611)

In [19]:
arr2.argmin()

np.int64(0)

In [20]:
arr2.argmax()

np.int64(8)

In [21]:
## Reshaping and resizing

In [22]:
arr3 = np.arange(1,31)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [23]:
arr3.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])