In [1]:
import numpy as np

In [6]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Indexing and slicing


In [9]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[4]

np.int64(15)

In [11]:
#slice

In [12]:
arr[1:5]

array([12, 13, 14, 15])

In [13]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr[3::2]

array([14, 16, 18, 20])

In [15]:
#for Matrix

In [17]:
arr2  = np.arange(1,31).reshape(6,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [18]:
arr2[1]

array([ 6,  7,  8,  9, 10])

In [19]:
arr2[0]

array([1, 2, 3, 4, 5])

In [21]:
arr2[3]

array([16, 17, 18, 19, 20])

In [22]:
arr2[0,3]

np.int64(4)

In [23]:
arr2[5,4]

np.int64(30)

In [25]:
arr2[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [26]:
arr2[3:6,2:5]

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [27]:
arr2[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [28]:
arr2[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])